In [11]:
import time    
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

data=[[],[0,0,0]]

with Chrome(executable_path=r'C:\Program Files\chromedriver.exe') as driver:
    wait = WebDriverWait(driver,15)
    driver.get("https://www.youtube.com/watch?v=SukwNeHMMhQ")

    for item in range(50): 
        wait.until(EC.visibility_of_element_located((By.TAG_NAME, "body"))).send_keys(Keys.END)
        time.sleep(4)

    for comment in wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "#content"))):
        data[0].append(comment.text)
    for likes in wait.until(EC.presence_of_all_elements_located((By.CSS_SELECTOR, "#toolbar"))):
        data[1].append(likes.text)

C:\Users\Peter\AppData\Local\Temp\ipykernel_15348\2893157800.py:10: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  with Chrome(executable_path=r'C:\Program Files\chromedriver.exe') as driver:

In [94]:
import pandas as pd

comment = data[0]
likes = data[1]
data_tuples = list(zip(comment,likes))
df = pd.DataFrame(data_tuples, columns=['comment','likes'])
df.head(10)

                                             comment       likes
0  Skip navigation\nSign in\n1:03\nCoke 2012 Comm...           0
1                                                              0
2                                                              0
3                              Such a beautiful poem       Reply
4  It's been a while i bought any type of soda or...    1\nReply
5  I literally just had a dream about 2 people or...       Reply
6  Bring back original coca cola song ..I'd like ...    3\nReply
7                                          THIS POEM       Reply
8  Probably the most optimistically Orwellian adv...  158\nReply
9  Maravilhosa essa propaganda. N贸s faz sentir qu...       Reply

In [95]:
df_d = df.drop([0,1,2], axis=0)
df_dr = df_d.reset_index()
df_dr = df_dr.drop("index", axis=1)
df_dr.head(10)

                                             comment       likes
0                              Such a beautiful poem       Reply
1  It's been a while i bought any type of soda or...    1\nReply
2  I literally just had a dream about 2 people or...       Reply
3  Bring back original coca cola song ..I'd like ...    3\nReply
4                                          THIS POEM       Reply
5  Probably the most optimistically Orwellian adv...  158\nReply
6  Maravilhosa essa propaganda. N贸s faz sentir qu...       Reply
7  Yeah, what if we are #OpenLikeNeverBefore and ...    7\nReply
8                              Like Never Before....       Reply
9                  Sooooo many awake people in here     7\nReply

In [96]:
import re
import numpy as np
#iterate through all entries of likes column and substitute line breaks (\n) and Reply with an empty string
for i in range(len(df_dr)): 
    x = df_dr.likes[i]
    x = re.sub("[\nReply]", "", x)
    df_dr.likes[i] = x

df_dr.head()

                                             comment likes
0                              Such a beautiful poem
1  It's been a while i bought any type of soda or...     1
2  I literally just had a dream about 2 people or...
3  Bring back original coca cola song ..I'd like ...     3
4                                          THIS POEM

In [97]:
#drop rows with empty values in comment column
df_dr['comment'].replace('', np.nan, inplace=True) #replace empty comments (probably emojis) with numpy nan so that it can be recognized by Pandas
df_dr = df_dr.dropna(axis=0,subset=['comment']) #drop all rows that have nothing in the comment column
df_dr = df_dr.reset_index() #reset index
df_dr = df_dr.drop("index", axis=1) #drop the residual index number

df_dr.head()

                                             comment likes
0                              Such a beautiful poem
1  It's been a while i bought any type of soda or...     1
2  I literally just had a dream about 2 people or...
3  Bring back original coca cola song ..I'd like ...     3
4                                          THIS POEM

In [98]:
df_dr.to_csv("CocaCola_George_the_Poet.csv") #save Pandas Dataframe to CSV file